name: ${pluginName}
version: "${projectVersion}"
main: ${mainClass}
description: "${pluginDescription}"
author: ${pluginAuthor}
website: ${pluginWebsite}
api-version: "1.19"

folia-supported: true

has-open-classloader: true

dependencies:
  - name: PlaceholderAPI
    required: false
    bootstrap: false

load-after:
  - name: ProtocolLib
    bootstrap: true