name: Triton
version: "4.0.0-SNAPSHOT"
main: com.rexcantor64.triton.spigot.plugin.SpigotPlugin
description: "A plugin that replaces any message on your server, to the receiver's\
  \ language, in real time!"
author: Rexcantor64
website: https://triton.rexcantor64.com/
api-version: "1.19"

folia-supported: true

dependencies:
  - name: ProtocolLib
    required: true
    bootstrap: true
  - name: PlaceholderAPI
    required: false
    bootstrap: true

commands:
  twin:
    description: Upload and download your config to/from the Triton Web INterface.
    usage: "/twin [code]"
permissions:
  triton.database:
    default: op
  triton.getflag:
    default: op
  triton.help:
    default: "true"
  triton.info:
    default: "true"
  triton.loglevel:
    default: op
  triton.openselector:
    default: "true"
  triton.reload:
    default: op
  triton.setlanguage:
    default: "true"
  triton.setlanguage.others:
    default: op
  triton.sign:
    default: op
  twin.download:
    default: op
  twin.upload:
    default: op